default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: rantly_development

test:
  <<: *default
  database: rantly_test

production:
  <<: *default
  database: rantly_production
  username: rantly
  password: <%= ENV['RANTLY_DATABASE_PASSWORD'] %>
